pystray._base - ERROR - An error occurred when calling message handler
Traceback (most recent call last):
  File "D:\programming\Projects\self\skype_alert\.venv\Lib\site-packages\pystray\_win32.py", line 412, in _dispatcher
    return int(icon._message_handlers.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programming\Projects\self\skype_alert\.venv\Lib\site-packages\pystray\_win32.py", line 224, in _on_notify
    descriptors[index - 1](self)
  File "D:\programming\Projects\self\skype_alert\.venv\Lib\site-packages\pystray\_base.py", line 328, in inner
    callback(self)
  File "D:\programming\Projects\self\skype_alert\.venv\Lib\site-packages\pystray\_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programming\Projects\self\skype_alert\main.py", line 235, in <lambda>
    menu = (pystray.MenuItem('Exit', lambda icon, item: exit_action(icon, item, skEvent)),)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\programming\Projects\self\skype_alert\main.py", line 245, in exit_action
    skEvent.onEvent(SkypeCallEvent())
  File "D:\programming\Projects\self\skype_alert\main.py", line 45, in onEvent
    sys.exit()
SystemExit
